version: '3'
services:

  nginx:
    build: ./nginx_server
    image: nginx:stable
    expose:
      - "8080"
    volumes:
      - ./nginx_server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_server/website/troweld-html:/var/www/html
    labels:
      - traefik.http.routers.my-container.rule=Host(`localhost`)

  api:
    build: ./api
    expose:
      - "7000"
    labels:
      - traefik.http.routers.my-container.rule=Host(`localhost/api`)


  reverse-proxy:
    image: traefik:v2.10
    command: --providers.docker
             --api.dashboard=true
             --api.insecure=true
    ports:
      - "80:80"
      - "7080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock