version: '3'
services:
  nginx:
    build: ./nginx_server
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx_server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_server/website/troweld-html:/var/www/html

  api:
    build: ./api
    ports:
      - "7000:7000"