version: '3'
services:
  api:
    build: ./api

    expose:
      - "7000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"

  nginx:
    build: ./nginx_server
    image: nginx:stable
    expose:
      - "80"
    volumes:
      - ./nginx_server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_server/website/troweld-html:/var/www/html
    labels:
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"


  reverse-proxy:
    image: traefik:v2.10
    command: --providers.docker
             --api.dashboard=true
             --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
      -
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock