version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./website/troweld-html:/var/www/html
